/// Distinct list of consoles/platforms.
table DimConsole
	lineageTag: 4be7bafc-62ec-4d82-b3e6-4c2eae946d98

	column Console
		dataType: string
		isNullable: false
		lineageTag: bc81f648-17d7-4905-83c8-1d5e781889c6
		sourceColumn: Console

	column ConsoleKey
		dataType: string
		isNullable: false
		isHidden: true
		lineageTag: 5d0ca863-db55-44e0-8523-b865fda98a3e
		sourceColumn: ConsoleKey

	partition DimConsole = m
		mode: import
		source =
				let
				    Source = VideoGameSalesTypedSource,
				    KeepColumns = Table.SelectColumns(Source, {"console"}),
				    AddedConsole = Table.AddColumn(KeepColumns, "Console", each NormalizeCategoryLabel([console]), type text),
				    AddedColumns = Table.AddColumn(AddedConsole, "ConsoleKey", each NormalizeCategoryKey([console]), type text),
				    SelectedColumns = Table.SelectColumns(AddedColumns, {"Console", "ConsoleKey"}),
				    SortedRows = Table.Sort(SelectedColumns, {{"Console", Order.Ascending}}),
				    DistinctRows = Table.Distinct(SortedRows, {"ConsoleKey"})
				in
				    DistinctRows

