/// Distinct list of developers.
table DimDeveloper
	lineageTag: 7fa10d9d-972c-42c0-83e1-f6ef4262bde8

	column Developer
		dataType: string
		isNullable: false
		lineageTag: dd5341d8-aaf8-44ad-b6dc-2c055b42305d
		sourceColumn: Developer

	column DeveloperKey
		dataType: string
		isNullable: false
		isHidden: true
		lineageTag: 9ab0b84a-3286-4fdd-a8fa-62148a8d1309
		sourceColumn: DeveloperKey

	partition DimDeveloper = m
		mode: import
		source =
				let
				    Source = VideoGameSalesTypedSource,
				    KeepColumns = Table.SelectColumns(Source, {"developer"}),
				    AddedDeveloper = Table.AddColumn(KeepColumns, "Developer", each NormalizeCategoryLabel([developer]), type text),
				    AddedColumns = Table.AddColumn(AddedDeveloper, "DeveloperKey", each NormalizeCategoryKey([developer]), type text),
				    SelectedColumns = Table.SelectColumns(AddedColumns, {"Developer", "DeveloperKey"}),
				    SortedRows = Table.Sort(SelectedColumns, {{"Developer", Order.Ascending}}),
				    DistinctRows = Table.Distinct(SortedRows, {"DeveloperKey"})
				in
				    DistinctRows

