/// Distinct list of genres.
table DimGenre
	lineageTag: a3664a1c-b4b1-4d77-a76e-2b2174abfe46

	column Genre
		dataType: string
		isNullable: false
		lineageTag: e33f311c-bbb3-4efd-812c-7a3a0593ba69
		sourceColumn: Genre

	column GenreKey
		dataType: string
		isNullable: false
		isHidden: true
		lineageTag: 4879d04a-c286-4927-a6ef-f179fb8c2fbb
		sourceColumn: GenreKey

	partition DimGenre = m
		mode: import
		source =
				let
				    Source = VideoGameSalesTypedSource,
				    KeepColumns = Table.SelectColumns(Source, {"genre"}),
				    AddedColumns = Table.AddColumns(
				        KeepColumns,
				        {
				            {"Genre", each NormalizeCategoryLabel([genre]), type text},
				            {"GenreKey", each NormalizeCategoryKey([genre]), type text}
				        }
				    ),
				    SelectedColumns = Table.SelectColumns(AddedColumns, {"Genre", "GenreKey"}),
				    SortedRows = Table.Sort(SelectedColumns, {{"Genre", Order.Ascending}}),
				    DistinctRows = Table.Distinct(SortedRows, {"GenreKey"})
				in
				    DistinctRows

