/// Distinct list of publishers.
table DimPublisher
	lineageTag: 218a5a20-f8d1-4ac5-a734-eb9667995b1b

	column Publisher
		dataType: string
		isNullable: false
		lineageTag: cc97de66-86b0-469a-b75b-493065e5ec0f
		sourceColumn: Publisher

	column PublisherKey
		dataType: string
		isNullable: false
		isHidden: true
		lineageTag: 9e46910f-8c03-4fa8-b41a-c88e9ac0b4de
		sourceColumn: PublisherKey

	partition DimPublisher = m
		mode: import
		source =
				let
				    Source = VideoGameSalesTypedSource,
				    KeepColumns = Table.SelectColumns(Source, {"publisher"}),
				    AddedColumns = Table.AddColumns(
				        KeepColumns,
				        {
				            {"Publisher", each NormalizeCategoryLabel([publisher]), type text},
				            {"PublisherKey", each NormalizeCategoryKey([publisher]), type text}
				        }
				    ),
				    SelectedColumns = Table.SelectColumns(AddedColumns, {"Publisher", "PublisherKey"}),
				    SortedRows = Table.Sort(SelectedColumns, {{"Publisher", Order.Ascending}}),
				    DistinctRows = Table.Distinct(SortedRows, {"PublisherKey"})
				in
				    DistinctRows

